spring.application.name=dnd-spellbook-eindopdracht-novi

#Database
spring.datasource.url=jdbc:postgresql://localhost:5432/dnd-spellbook
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/dnd-spellbook

