-- Classes
INSERT INTO classes (class_name, description)
VALUES ('Bard', 'An inspiring magician whose power echoes the music of creation.')
    ON CONFLICT (class_name) DO NOTHING;

INSERT INTO classes (class_name, description)
VALUES ('Cleric', 'A priestly champion who wields divine magic in service of a higher power.')
    ON CONFLICT (class_name) DO NOTHING;

INSERT INTO classes (class_name, description)
VALUES ('Druid', 'A priest of the Old Faith, wielding the powers of nature and adopting animal forms.')
    ON CONFLICT (class_name) DO NOTHING;

INSERT INTO classes (class_name, description)
VALUES ('Paladin', 'A holy warrior bound to a sacred oath.')
    ON CONFLICT (class_name) DO NOTHING;

INSERT INTO classes (class_name, description)
VALUES ('Ranger', 'A master of ranged combat, one with nature.')
    ON CONFLICT (class_name) DO NOTHING;

INSERT INTO classes (class_name, description)
VALUES ('Sorcerer', 'A magic user who draws their power from within.')
    ON CONFLICT (class_name) DO NOTHING;

INSERT INTO classes (class_name, description)
VALUES ('Warlock', 'A user of magic that is pacted to a powerful entity.')
    ON CONFLICT (class_name) DO NOTHING;

INSERT INTO classes (class_name, description)
VALUES ('Wizard', 'A scholarly magic-user who casts spells through study and intelligence.')
    ON CONFLICT (class_name) DO NOTHING;


-- Spells

INSERT INTO spells (spell_name, level, casting_time, range, components, duration, concentration, description)
VALUES
    ('Fire Bolt', 0, 'ACTION', 120, 'V, S', 'Instantaneous', false, 'You hurl a mote of fire at a creature or object within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 fire damage. A flammable object hit by this spell ignites if it isn''t being worn or carried.'),
    ('Mage Hand', 0, 'ACTION', 30, 'V, S', '1 minute', false, 'A spectral, floating hand appears at a point you choose within range. The hand lasts for the duration or until you dismiss it as an action. The hand vanishes if it is ever more than 30 feet away from you or if you cast this spell again. You can use your action to control the hand. You can use the hand to manipulate an object, open an unlocked door or container, stow or retrieve an item from an open container, or pour the contents out of a vial. You can move the hand up to 30 feet each time you use it. The hand can''t attack, activate magical items, or carry more than 10 pounds.'),
    ('Prestidigitation', 0, 'ACTION', 10, 'V, S', 'Up to 1 hour', false, 'This spell is a minor magical trick that novice spellcasters use for practice. You create one of the following magical effects within range: you create an instantaneous, harmless sensory effect, such as a shower of sparks, a puff of wind, faint musical notes, or an odd odor; you instantaneously light or snuff out a candle, a torch, or a small campfire; you instantaneously clean or soil an object no larger than 1 cubic foot; you chill, warm, or flavor up to 1 cubic foot of nonliving material for 1 hour; you make a color, a small mark, or a symbol appear on an object or a surface for 1 hour; or you create a nonmagical trinket or an illusory image that can fit in your hand and that lasts until the end of your next turn. If you cast this spell multiple times, you can have up to three of its non-instantaneous effects active at a time, and you can dismiss such an effect as an action.'),
    ('Sacred Flame', 0, 'ACTION', 60, 'V, S', 'Instantaneous', false, 'Flame-like radiance descends on a creature that you can see within range. The target must succeed on a Dexterity saving throw or take 1d8 radiant damage. The target gains no benefit from cover for this saving throw. The spell''s damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).'),
    ('Guidance', 0, 'ACTION', 0, 'V, S', 'Concentration, up to 1 minute', true, 'You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice. It can roll the die before or after making the ability check. The spell then ends.'),
    ('Toll the Dead', 0, 'ACTION', 60, 'V, S', 'Instantaneous', false, 'You point at one creature you can see within range, and the sound of a dolorous bell fills the air around it for a moment. The target must succeed on a Wisdom saving throw or take 1d8 necrotic damage. If the target is missing any of its hit points, it instead takes 1d12 necrotic damage. The spell''s damage increases by one die when you reach 5th level (2d8 or 2d12), 11th level (3d8 or 3d12), and 17th level (4d8 or 4d12).'),
    ('Vicious Mockery', 0, 'ACTION', 60, 'V', 'Instantaneous', false, 'You unleash a string of insults laced with subtle enchantments at a creature you can see within range. If the target can hear you (though it need not understand you), it must succeed on a Wisdom saving throw or take 1d4 psychic damage and have disadvantage on the next attack roll it makes before the end of its next turn. This spell''s damage increases by 1d4 when you reach 5th level (2d4), 11th level (3d4), and 17th level (4d4).'),
    ('Shillelagh', 0, 'BONUS_ACTION', 0, 'V, S, M', '1 minute', false, 'The wood of a club or quarterstaff you are holding is imbued with nature''s power. For the duration, you can use your spellcasting ability instead of Strength for the attack and damage rolls of melee attacks using that weapon, and the weapon''s damage die becomes a d8. The weapon also becomes magical, if it isn''t already. The spell ends if you cast it again or if you let go of the weapon.'),
    ('Eldritch Blast', 0, 'ACTION', 120, 'V, S', 'Instantaneous', false, 'A beam of crackling energy streaks toward a creature within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 force damage. The spell creates more than one beam when you reach higher levels: two beams at 5th level, three beams at 11th level, and four beams at 17th level. You can direct the beams at the same target or at different ones. Make a separate attack roll for each beam.'),
    ('Thunderclap', 0, 'ACTION', 5, 'S', 'Instantaneous', false, 'You create a burst of thunderous sound that can be heard up to 100 feet away. Each creature within range, other than you, must succeed on a Constitution saving throw or take 1d6 thunder damage. The spell''s damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).'),

    ('Cure Wounds', 1, 'ACTION', 0, 'V, S', 'Instantaneous', false, 'A creature you touch regains a number of hit points equal to 1d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs. At higher levels: When you cast this spell using a spell slot of 2nd level or higher, the healing increases by 1d8 for each slot level above 1st.'),
    ('Bless', 1, 'ACTION', 30, 'V, S, M', 'Concentration, up to 1 minute', true, 'You bless up to three creatures of your choice within range. Whenever a target makes an attack roll or a saving throw before the spell ends, the target can roll a d4 and add the number rolled to the attack roll or saving throw. At higher levels: When you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st.'),
    ('Magic Missile', 1, 'ACTION', 120, 'V, S', 'Instantaneous', false, 'You create three glowing darts of magical force. Each dart hits a creature of your choice that you can see within range. A dart deals 1d4 + 1 force damage to its target. The darts all strike simultaneously, and you can direct them to hit one creature or several. At higher levels: When you cast this spell using a spell slot of 2nd level or higher, the spell creates one more dart for each slot level above 1st.'),
    ('Shield', 1, 'REACTION', 0, 'V, S', '1 round', false, 'An invisible barrier of magical force appears and protects you. Until the start of your next turn, you have a +5 bonus to AC, including against the triggering attack, and you take no damage from magic missile.'),
    ('Healing Word', 1, 'BONUS_ACTION', 60, 'V', 'Instantaneous', false, 'A creature of your choice that you can see within range regains hit points equal to 1d4 + your spellcasting ability modifier. This spell has no effect on undead or constructs. At higher levels: When you cast this spell using a spell slot of 2nd level or higher, the healing increases by 1d4 for each slot level above 1st.'),
    ('Detect Magic', 1, 'ACTION', 0, 'V, S', 'Concentration, up to 10 minutes', true, 'For the duration, you sense the presence of magic within 30 feet of you. If you sense magic in this way, you can use your action to see a faint aura around any visible creature or object in the area that bears magic, and you learn its school of magic, if any. The spell can penetrate most barriers, but it is blocked by 1 foot of stone, 1 inch of common metal, a thin sheet of lead, or 3 feet of wood or dirt.'),
    ('Hex', 1, 'BONUS_ACTION', 90, 'V, S, M', 'Concentration, up to 1 hour', true, 'You place a curse on a creature that you can see within range. Until the spell ends, you deal an extra 1d6 necrotic damage to the target whenever you hit it with an attack. Also, choose one ability when you cast the spell. The target has disadvantage on ability checks made with the chosen ability. If the target drops to 0 hit points before this spell ends, you can use a bonus action on a subsequent turn of yours to curse a new creature. At higher levels: When you cast this spell using a spell slot of 3rd or 4th level, you can maintain your concentration on the spell for up to 8 hours. When you use a spell slot of 5th level or higher, you can maintain your concentration on the spell for up to 24 hours.'),
    ('Entangle', 1, 'ACTION', 90, 'V, S', 'Concentration, up to 1 minute', true, 'Grasping weeds and vines sprout from the ground in a 20-foot square starting from a point within range. For the duration, these plants turn the ground in the area into difficult terrain. A creature in the area when you cast the spell must succeed on a Strength saving throw or be restrained by the entangling plants until the spell ends. A creature restrained by the plants can use its action to make a Strength check against your spell save DC. On a success, it frees itself.'),
    ('Divine Smite', 1, 'ACTION', 0, 'V', 'Instantaneous', false, 'When you hit a creature with a melee weapon attack, you can expend one spell slot to deal radiant damage to the target, in addition to the weapon''s damage. The extra damage is 2d8 for a 1st-level spell slot, plus 1d8 for each spell level higher than 1st, to a maximum of 5d8. The damage increases by 1d8 if the target is an undead or a fiend, to a maximum of 6d8.'),
    ('Dissonant Whispers', 1, 'ACTION', 60, 'V', 'Instantaneous', false, 'You whisper a discordant melody that only one creature of your choice within range can hear, wracking it with terrible pain. The target must make a Wisdom saving throw. On a failed save, it takes 3d6 psychic damage and must immediately use its reaction, if available, to move as far as its speed allows away from you. The creature doesn''t move into obviously dangerous ground, such as a fire or a pit. On a successful save, the target takes half as much damage and doesn''t have to move away. At higher levels: When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d6 for each slot level above 1st.'),
    ('Hunter''s Mark', 1, 'BONUS_ACTION', 90, 'V', 'Concentration, up to 1 hour', true, 'You choose a creature you can see within range and mystically mark it as your quarry. Until the spell ends, you deal an extra 1d6 damage to the target whenever you hit it with a weapon attack, and you have advantage on any Wisdom (Perception) or Wisdom (Survival) check you make to find it. If the target drops to 0 hit points before this spell ends, you can use a bonus action on a subsequent turn of yours to mark a new creature. At higher levels: When you cast this spell using a spell slot of 3rd or 4th level, you can maintain your concentration on the spell for up to 8 hours. When you use a spell slot of 5th level or higher, you can maintain your concentration for up to 24 hours.'),

    ('Misty Step', 2, 'BONUS_ACTION', 0, 'V', 'Instantaneous', false, 'Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space that you can see.'),
    ('Hold Person', 2, 'ACTION', 60, 'V, S, M', 'Concentration, up to 1 minute', true, 'Choose a humanoid that you can see within range. The target must succeed on a Wisdom saving throw or be paralyzed for the duration. At the end of each of its turns, the target can make another Wisdom saving throw. On a success, the spell ends on the target. At higher levels: When you cast this spell using a spell slot of 3rd level or higher, you can target one additional humanoid for each slot level above 2nd. The humanoids must be within 30 feet of each other when you target them.'),
    ('Scorching Ray', 2, 'ACTION', 120, 'V, S', 'Instantaneous', false, 'You create three rays of fire and hurl them at targets within range. You can hurl them at one target or several. Make a ranged spell attack for each ray. On a hit, the target takes 2d6 fire damage. At higher levels: When you cast this spell using a spell slot of 3rd level or higher, you create one additional ray for each slot level above 2nd.'),
    ('Spiritual Weapon', 2, 'BONUS_ACTION', 60, 'V, S', '1 minute', false, 'You create a floating, spectral weapon within range that lasts for the duration or until you cast this spell again. When you cast the spell, you can make a melee spell attack against a creature within 5 feet of the weapon. On a hit, the target takes force damage equal to 1d8 + your spellcasting ability modifier. As a bonus action on your turn, you can move the weapon up to 20 feet and repeat the attack against a creature within 5 feet of it. The weapon can take whatever form you choose. At higher levels: When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d8 for every two slot levels above 2nd.'),
    ('Moonbeam', 2, 'ACTION', 120, 'V, S, M', 'Concentration, up to 1 minute', true, 'A silvery beam of pale light shines down in a 5-foot-radius, 40-foot-high cylinder centered on a point within range. Until the spell ends, dim light fills the cylinder. When a creature enters the spell''s area for the first time on a turn or starts its turn there, it is engulfed in ghostly flames that cause searing pain, and it must make a Constitution saving throw. It takes 2d10 radiant damage on a failed save, or half as much damage on a successful one. A shapechanger makes its saving throw with disadvantage. If it fails, it also instantly reverts to its original form and can''t assume a different form until it leaves the spell''s light. At higher levels: When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d10 for each slot level above 2nd.'),
    ('Shatter', 2, 'ACTION', 60, 'V, S, M', 'Instantaneous', false, 'A sudden loud ringing noise, painfully intense, erupts from a point of your choice within range. Each creature in a 10-foot-radius sphere centered on that point must make a Constitution saving throw. A creature takes 3d8 thunder damage on a failed save, or half as much damage on a successful one. A creature made of inorganic material such as stone, crystal, or metal has disadvantage on this saving throw. A nonmagical object that isn''t being worn or carried also takes the damage if it''s in the spell''s area. At higher levels: When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d8 for each slot level above 2nd.'),
    ('Aid', 2, 'ACTION', 30, 'V, S, M', '8 hours', false, 'Your spell bolsters your allies with toughness and resolve. Choose up to three creatures within range. Each target''s hit point maximum and current hit points increase by 5 for the duration. At higher levels: When you cast this spell using a spell slot of 3rd level or higher, a target''s hit points increase by an additional 5 for each slot level above 2nd.'),

    ('Fireball', 3, 'ACTION', 150, 'V, S, M', 'Instantaneous', false, 'A bright streak flashes from your pointing finger to a point you choose within range and then blossoms with a low roar into an explosion of flame. Each creature in a 20-foot-radius sphere centered on that point must make a Dexterity saving throw. A target takes 8d6 fire damage on a failed save, or half as much damage on a successful one. The fire spreads around corners. It ignites flammable objects in the area that aren''t being worn or carried. At higher levels: When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.'),
    ('Counterspell', 3, 'REACTION', 60, 'S', 'Instantaneous', false, 'You attempt to interrupt a creature in the process of casting a spell. If the creature is casting a spell of 3rd level or lower, its spell fails and has no effect. If it is casting a spell of 4th level or higher, make an ability check using your spellcasting ability. The DC equals 10 + the spell''s level. On a success, the creature''s spell fails and has no effect. At higher levels: When you cast this spell using a spell slot of 4th level or higher, the interrupted spell has no effect if its level is less than or equal to the level of the spell slot you used.'),
    ('Mass Healing Word', 3, 'BONUS_ACTION', 60, 'V', 'Instantaneous', false, 'As you call out words of restoration, up to six creatures of your choice that you can see within range regain hit points equal to 1d4 + your spellcasting ability modifier. This spell has no effect on undead or constructs. At higher levels: When you cast this spell using a spell slot of 4th level or higher, the healing increases by 1d4 for each slot level above 3rd.'),
    ('Spirit Guardians', 3, 'ACTION', 0, 'V, S, M', 'Concentration, up to 10 minutes', true, 'You call forth spirits to protect you. They flit around you to a distance of 15 feet for the duration. If you are good or neutral, their spectral form appears angelic or fey (your choice). If you are evil, they appear fiendish. When you cast this spell, you can designate any number of creatures you can see to be unaffected by it. An affected creature''s speed is halved in the area, and when the creature enters the area for the first time on a turn or starts its turn there, it must make a Wisdom saving throw. On a failed save, the creature takes 3d8 radiant damage (if you are good or neutral) or 3d8 necrotic damage (if you are evil). On a successful save, the creature takes half as much damage. At higher levels: When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d8 for each slot level above 3rd.'),
    ('Call Lightning', 3, 'ACTION', 120, 'V, S', 'Concentration, up to 10 minutes', true, 'A storm cloud appears in the shape of a cylinder that is 10 feet tall with a 60-foot radius, centered on a point you can see within range directly above you. The spell fails if you can''t see a point in the air where the storm cloud could appear. When you cast the spell, choose a point you can see under the cloud. A bolt of lightning flashes down from the cloud to that point. Each creature within 5 feet of that point must make a Dexterity saving throw. A creature takes 3d10 lightning damage on a failed save, or half as much damage on a successful one. On each of your turns until the spell ends, you can use your action to call lightning in this way again, targeting the same point or a different one. If you are outdoors in stormy conditions when you cast this spell, the spell gives you control over the existing storm instead, and the spell''s damage increases by 1d10. At higher levels: When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d10 for each slot level above 3rd.'),
    ('Hypnotic Pattern', 3, 'ACTION', 120, 'V, S, M', 'Concentration, up to 1 minute', true, 'You create a twisting pattern of colors that weaves through the air inside a 30-foot cube within range. The pattern appears for a moment and vanishes. Each creature in the area who sees the pattern must make a Wisdom saving throw. On a failed save, the creature becomes charmed for the duration. While charmed by this spell, the creature is incapacitated and has a speed of 0. The spell ends for an affected creature if it takes any damage or if someone else uses an action to shake the creature out of its stupor.'),
    ('Hunger of Hadar', 3, 'ACTION', 150, 'V, S, M', 'Concentration, up to 1 minute', true, 'You open a gateway to the dark between the stars, a region infested with unknown horrors. A 20-foot-radius sphere of blackness and bitter cold appears, centered on a point with range and lasting for the duration. This void is filled with a cacophony of soft whispers and slurping noises that can be heard up to 30 feet away. No light, magical or otherwise, can illuminate the area, and creatures fully within the area are blinded. The void creates a warp in the fabric of space, and the area is difficult terrain. Any creature that starts its turn in the area takes 2d6 cold damage. Any creature that ends its turn in the area must succeed on a Dexterity saving throw or take 2d6 acid damage as milky, otherworldly tentacles rub against it.'),
    ('Conjure Animals', 3, 'ACTION', 60, 'V, S', 'Concentration, up to 1 hour', true, 'You summon fey spirits that take the form of beasts and appear in unoccupied spaces that you can see within range. Choose one of the following options for what appears: one beast of challenge rating 2 or lower, two beasts of challenge rating 1 or lower, four beasts of challenge rating 1/2 or lower, or eight beasts of challenge rating 1/4 or lower. Each beast is also considered fey, and it disappears when it drops to 0 hit points or when the spell ends. The summoned creatures are friendly to you and your companions. Roll initiative for the summoned creatures as a group, which has its own turns. They obey any verbal commands that you issue to them (no action required by you). If you don''t issue any commands to them, they defend themselves from hostile creatures, but otherwise take no actions. At higher levels: When you cast this spell using certain higher-level spell slots, you choose one of the summoning options above, and more creatures appear: twice as many with a 5th-level slot, three times as many with a 7th-level slot, and four times as many with a 9th-level slot.'),

    ('Banishment', 4, 'ACTION', 60, 'V, S, M', 'Concentration, up to 1 minute', true, 'You attempt to send one creature that you can see within range to another plane of existence. The target must succeed on a Charisma saving throw or be banished. If the target is native to the plane of existence you''re on, you banish the target to a harmless demiplane. While there, the target is incapacitated. The target remains there until the spell ends, at which point the target reappears in the space it left or in the nearest unoccupied space if that space is occupied. If the target is native to a different plane of existence than the one you''re on, the target is banished with a faint popping noise, returning to its home plane. If the spell ends before 1 minute has passed, the target reappears in the space it left or in the nearest unoccupied space if that space is occupied. Otherwise, the target doesn''t return. At higher levels: When you cast this spell using a spell slot of 5th level or higher, you can target one additional creature for each slot level above 4th.'),
    ('Arcane Eye', 4, 'ACTION', 30, 'V, S, M', 'Concentration, up to 1 hour', true, 'You create an invisible, magical eye within range that hovers in the air for the duration. You mentally receive visual information from the eye, which has normal vision and darkvision out to 30 feet. The eye can look in every direction. As an action, you can move the eye up to 30 feet in any direction. There is no limit to how far away from you the eye can move, but it can''t enter another plane of existence. A solid barrier blocks the eye''s movement, but the eye can pass through an opening as small as 1 inch in diameter.'),
    ('Guardian of Faith', 4, 'ACTION', 30, 'V', '8 hours', false, 'A Large spectral guardian appears and hovers for the duration in an unoccupied space of your choice that you can see within range. The guardian occupies that space and is indistinct except for a gleaming sword and shield emblazoned with the symbol of your deity. Any creature hostile to you that moves to a space within 10 feet of the guardian for the first time on a turn must succeed on a Dexterity saving throw. The creature takes 20 radiant damage on a failed save, or half as much damage on a successful one. The guardian vanishes when it has dealt a total of 60 damage.'),
    ('Polymorph', 4, 'ACTION', 60, 'V, S, M', 'Concentration, up to 1 hour', true, 'This spell transforms a creature that you can see within range into a new form. An unwilling creature must make a Wisdom saving throw to avoid the effect. A shapechanger automatically succeeds on this saving throw. The spell has no effect on a target that is already transformed. The transformation lasts for the duration, or until the target drops to 0 hit points or dies. The new form can be any beast whose challenge rating is equal to or less than the target''s (or the target''s level, if it doesn''t have a challenge rating). The target''s game statistics, including mental ability scores, are replaced by the statistics of the chosen beast.'),
    ('Blight', 4, 'ACTION', 30, 'V, S', 'Instantaneous', false, 'Necromantic energy washes over a creature of your choice that you can see within range, draining moisture and vitality from it. The target must make a Constitution saving throw. The target takes 8d8 necrotic damage on a failed save, or half as much damage on a successful one. This spell has no effect on undead or constructs. If you target a plant creature or a magical plant, it makes the saving throw with disadvantage, and the spell deals maximum damage to it. If you target a nonmagical plant that isn''t a creature, such as a tree or shrub, it doesn''t make a saving throw; it simply withers and dies. At higher levels: When you cast this spell using a spell slot of 5th level or higher, the damage increases by 1d8 for each slot level above 4th.'),
    ('Dominate Beast', 4, 'ACTION', 60, 'V, S', 'Concentration, up to 1 minute', true, 'You attempt to beguile a beast that you can see within range. It must succeed on a Wisdom saving throw or be charmed by you for the duration. If you or creatures that are friendly to you are fighting it, it has advantage on the saving throw. While the beast is charmed, you have a telepathic link with it as long as the two of you are on the same plane of existence. You can use this telepathic link to issue commands to the creature while you are conscious (no action required), which it does its best to obey. At higher levels: When you cast this spell using a 5th-level spell slot, the duration is concentration, up to 10 minutes. When you use a 6th-level spell slot, the duration is concentration, up to 1 hour. When you use a spell slot of 7th level or higher, the duration is concentration, up to 8 hours.'),

    ('Cone of Cold', 5, 'ACTION', 0, 'V, S, M', 'Instantaneous', false, 'A blast of cold air erupts from your hands. Each creature in a 60-foot cone must make a Constitution saving throw. A creature takes 8d8 cold damage on a failed save, or half as much damage on a successful one. A creature killed by this spell becomes a frozen statue until it thaws. At higher levels: When you cast this spell using a spell slot of 6th level or higher, the damage increases by 1d8 for each slot level above 5th.'),
    ('Scrying', 5, 'ACTION', 0, 'V, S, M', 'Concentration, up to 10 minutes', true, 'You can see and hear a particular creature you choose that is on the same plane of existence as you. The target must make a Wisdom saving throw, which is modified by how well you know the target and the sort of physical connection you have to it. If a target knows you''re casting this spell, it can fail the saving throw voluntarily if it wants to be observed. On a successful save, the target isn''t affected, and you can''t use this spell against it again for 24 hours. On a failed save, the spell creates an invisible sensor within 10 feet of the target. You can see and hear through the sensor as if you were there. The sensor moves with the target, remaining within 10 feet of it for the duration.'),
    ('Mass Cure Wounds', 5, 'ACTION', 60, 'V, S', 'Instantaneous', false, 'A wave of healing energy washes out from a point of your choice within range. Choose up to six creatures in a 30-foot-radius sphere centered on that point. Each target regains hit points equal to 3d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs. At higher levels: When you cast this spell using a spell slot of 6th level or higher, the healing increases by 1d8 for each slot level above 5th.'),
    ('Dominate Person', 5, 'ACTION', 60, 'V, S', 'Concentration, up to 1 minute', true, 'You attempt to beguile a humanoid that you can see within range. It must succeed on a Wisdom saving throw or be charmed by you for the duration. If you or creatures that are friendly to you are fighting it, it has advantage on the saving throw. While the target is charmed, you have a telepathic link with it as long as the two of you are on the same plane of existence. You can use this telepathic link to issue commands to the creature while you are conscious (no action required), which it does its best to obey. At higher levels: When you cast this spell using a 6th-level spell slot, the duration is concentration, up to 10 minutes. When you use a 7th-level spell slot, the duration is concentration, up to 1 hour. When you use a spell slot of 8th level or higher, the duration is concentration, up to 8 hours.'),
    ('Wrath of Nature', 5, 'ACTION', 120, 'V, S', 'Concentration, up to 1 minute', true, 'You call out to the spirits of nature to rouse them against your enemies. Choose a point you can see within range. The spirits cause trees, rocks, and grasses in a 60-foot cube centered on that point to become animated until the spell ends. Grasses and Undergrowth: Any area of ground in the cube that is covered by grass or undergrowth is difficult terrain for your enemies. Trees: At the start of each of your turns, each of your enemies within 10 feet of any tree in the cube must succeed on a Dexterity saving throw or take 4d6 slashing damage from whipping branches. Roots and Vines: At the end of each of your turns, one creature of your choice that is on the ground in the cube must succeed on a Strength saving throw or become restrained until the spell ends. Rocks: As a bonus action on your turn, you can cause a loose rock in the cube to launch at a creature you can see in the cube. Make a ranged spell attack against the target. On a hit, the target takes 3d8 nonmagical bludgeoning damage, and it must succeed on a Strength saving throw or fall prone.'),
    ('Destructive Wave', 5, 'ACTION', 0, 'V', 'Instantaneous', false, 'You strike the ground, creating a burst of divine energy that ripples outward from you. Each creature you choose within 30 feet of you must succeed on a Constitution saving throw or take 5d6 thunder damage, as well as 5d6 radiant or necrotic damage (your choice), and be knocked prone. A creature that succeeds on its saving throw takes half as much damage and isn''t knocked prone.'),

    ('Chain Lightning', 6, 'ACTION', 150, 'V, S, M', 'Instantaneous', false, 'You create a bolt of lightning that arcs toward a target of your choice that you can see within range. Three bolts then leap from that target to as many as three other targets, each of which must be within 30 feet of the first target. A target can be a creature or an object and can be targeted by only one of the bolts. A target must make a Dexterity saving throw. The target takes 10d8 lightning damage on a failed save, or half as much damage on a successful one. At higher levels: When you cast this spell using a spell slot of 7th level or higher, one additional bolt leaps from the first target to another target for each slot level above 6th.'),
    ('Harm', 6, 'ACTION', 60, 'V, S', 'Instantaneous', false, 'You unleash a virulent disease on a creature that you can see within range. The target must make a Constitution saving throw. On a failed save, it takes 14d6 necrotic damage, or half as much damage on a successful save. The damage can''t reduce the target''s hit points below 1. If the target fails the saving throw, its hit point maximum is reduced for 1 hour by an amount equal to the necrotic damage it took. Any effect that removes a disease allows a creature''s hit point maximum to return to normal before that time passes.'),
    ('Investiture of Flame', 6, 'ACTION', 0, 'V, S', 'Concentration, up to 10 minutes', true, 'Flames race across your body, shedding bright light in a 30-foot radius and dim light for an additional 30 feet for the spell''s duration. The flames don''t harm you. Until the spell ends, you gain the following benefits: you are immune to fire damage and have resistance to cold damage; any creature that moves within 5 feet of you for the first time on a turn or ends its turn there takes 1d10 fire damage; you can use your action to create a line of fire 15 feet long and 5 feet wide. Each creature in the line must make a Dexterity saving throw. A creature takes 4d8 fire damage on a failed save, or half as much damage on a successful one.'),
    ('Otto''s Irresistible Dance', 6, 'ACTION', 30, 'V', 'Concentration, up to 1 minute', true, 'Choose one creature that you can see within range. The target begins a comic dance in place: shuffling, tapping its feet, and capering for the duration. Creatures that can''t be charmed are immune to this spell. A dancing creature must use all its movement to dance without leaving its space and has disadvantage on Dexterity saving throws and attack rolls. While the target is affected by this spell, other creatures have advantage on attack rolls against it. As an action, a dancing creature makes a Wisdom saving throw to regain control of itself. On a successful save, the spell ends.'),

    ('Finger of Death', 7, 'ACTION', 60, 'V, S', 'Instantaneous', false, 'You send negative energy coursing through a creature that you can see within range, causing it searing pain. The target must make a Constitution saving throw. It takes 7d8 + 30 necrotic damage on a failed save, or half as much damage on a successful one. A humanoid killed by this spell rises at the start of your next turn as a zombie that is permanently under your command, following your verbal orders to the best of its ability.'),
    ('Resurrection', 7, 'ACTION', 0, 'V, S, M', 'Instantaneous', false, 'With a touch, you revive a dead creature that has been dead for no more than a century, didn’t die of old age, and wasn’t Undead when it died. The creature returns to life with all its Hit Points. This spell also neutralizes any poisons that affected the creature at the time of death. This spell closes all mortal wounds and restores any missing body parts. Coming back from the dead is an ordeal. The target takes a −4 penalty to D20 Tests. Every time the target finishes a Long Rest, the penalty is reduced by 1 until it becomes 0. Casting this spell to revive a creature that has been dead for 365 days or longer taxes you. Until you finish a Long Rest, you can’t cast spells again, and you have Disadvantage on D20 Tests.'),
    ('Etherealness', 7, 'ACTION', 0, 'V, S', '8 hours', false, 'You step into the border regions of the Ethereal Plane, in the area where it overlaps with your current plane. You remain in the Border Ethereal for the duration or until you use your action to dismiss the spell. During this time, you can move in any direction. If you move up or down, every foot of movement costs an extra foot. You can see and hear the plane you originated from, but everything there looks gray, and you can''t see anything more than 60 feet away. While on the Ethereal Plane, you can only affect and be affected by other creatures on that plane. Creatures that aren''t on the Ethereal Plane can''t perceive you and can''t interact with you, unless a special ability or magic has given them the ability to do so. You ignore all objects and effects that aren''t on the Ethereal Plane, allowing you to move through objects you perceive on the plane you originated from. When the spell ends, you immediately return to the plane you originated from in the spot you currently occupy. If you occupy the same spot as a solid object or creature when this happens, you are immediately shunted to the nearest unoccupied space that you can occupy and take force damage equal to twice the number of feet you are moved. This spell has no effect if you cast it while you are on the Ethereal Plane or a plane that doesn''t border it, such as one of the Outer Planes. At Higher Levels: When you cast this spell using a spell slot of 8th level or higher, you can target up to three willing creatures (including you) for each slot level above 7th. The creatures must be within 10 feet of you when you cast the spell.'),
    ('Mordenkainen''s Sword', 7, 'ACTION', 60, 'V, S, M', 'Concentration, up to 1 minute', true, 'You create a sword-shaped plane of force that hovers within range. It lasts for the duration. When the sword appears, you make a melee spell attack against a target of your choice within 5 feet of the sword. On a hit. the target takes 3d10 force damage. Until the spell ends, you can use a bonus action on each of your turns to move the sword up to 20 feet to a spot you can see and repeat this attack against the same target or a different one.'),

    ('Sunburst', 8, 'ACTION', 150, 'V, S, M', 'Instantaneous', false, 'Brilliant sunlight flashes in a 60-foot radius centered on a point you choose within range. Each creature in that light must make a Constitution saving throw. On a failed save, a creature takes 12d6 radiant damage and is blinded for 1 minute. On a successful save, it takes half as much damage and isn’t blinded by this spell. Undead and oozes have disadvantage on this saving throw. A creature blinded by this spell makes another Constitution saving throw at the end of each of its turns. On a successful save, it is no longer blinded. This spell dispels any darkness in its area that was created by a spell.'),
    ('Power Word Stun', 8, 'ACTION', 60, 'V', 'Instantaneous', false, 'You speak a word of power that can overwhelm the mind of one creature you can see within range, leaving it dumbfounded. If the target has 150 hit points or fewer, it is stunned. Otherwise, the spell has no effect. The stunned target must make a Constitution saving throw at the end of each of its turns. On a successful save, this stunning effect ends.'),
    ('Earthquake', 8, 'ACTION', 500, 'V, S, M', 'Concentration, up to 1 minute', true, 'You create a seismic disturbance at a point on the ground that you can see within range. For the duration, an intense tremor rips through the ground in a 100-foot-radius circle centered on that point and shakes creatures and structures in contact with the ground in that area. The ground in the area becomes difficult terrain. Each creature on the ground that is concentrating must make a Constitution saving throw. On a failed save, the creature’s concentration is broken. When you cast this spell and at the end of each turn you spend concentrating on it, each creature on the ground in the area must make a Dexterity saving throw. On a failed save, the creature is knocked prone.'),
    ('Holy Aura', 8, 'ACTION', 0, 'V, S, M', 'Concentration, up to 1 minute', true, 'Divine light washes out from you and coalesces in a soft radiance in a 30-foot radius around you. Creatures of your choice in that radius when you cast this spell shed dim light in a 5-foot radius and have advantage on all saving throws, and other creatures have disadvantage on attack rolls against them until the spell ends. In addition, when a fiend or an undead hits an affected creature with a melee attack, the aura flashes with brilliant light. The attacker must succeed on a Constitution saving throw or be blinded until the spell ends.'),

    ('Wish', 9, 'ACTION', 0, 'V', 'Instantaneous', false, 'Wish is the mightiest spell a mortal creature can cast. By simply speaking aloud, you can alter the very foundations of reality in accord with your desires. The basic use of this spell is to duplicate any other spell of 8th level or lower. You don''t need to meet any requirements in that spell, including costly components. The spell simply takes effect.'),
    ('Mass Heal', 9, 'ACTION', 60, 'V, S', 'Instantaneous', false, 'A flood of healing energy flows from you into injured creatures around you. You restore up to 700 hit points, divided as you choose among any number of creatures that you can see within range. Creatures healed by this spell are also cured of all diseases and any effect making them blinded or deafened. This spell has no effect on undead or constructs.'),
    ('Foresight', 9, 'ACTION', 0, 'V, S, M', '8 hours', false, 'You touch a willing creature and bestow a limited ability to see into the immediate future. For the duration, the target can’t be surprised and has advantage on attack rolls, ability checks, and saving throws. Additionally, other creatures have disadvantage on attack rolls against the target for the duration. This spell immediately ends if you cast it again before its duration ends.'),
    ('True Polymorph', 9, 'ACTION', 30, 'V, S, M', 'Concentration, up to 1 hour', true, 'Choose one creature with at least 1 hit point or nonmagical object that you can see within range. You transform the creature into a different creature, the creature into an object, or the object into a creature (the object must be neither worn nor carried by another creature). The transformation lasts for the duration, or until the target drops to 0 hit points or dies. If you concentrate on this spell for the full duration, the transformation becomes permanent.'),
    ('Storm of Vengeance', 9, 'ACTION', 0, 'V, S', 'Concentration, up to 1 minute', true, 'A churning storm cloud forms, centered on a point you can see and spreading to a radius of 360 feet. Lightning flashes in the area, thunder booms, and strong winds roar. Each creature under the cloud (no more than 5,000 feet beneath the cloud) when it appears must make a Constitution saving throw. On a failed save, a creature takes 2d6 thunder damage and becomes deafened for 5 minutes. Each round you maintain concentration on this spell, the storm produces different effects on your turn.')
    ON CONFLICT (spell_name) DO NOTHING;

-- Class - Spell Links

-- Bard
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Bard'), (SELECT id FROM spells WHERE spell_name = 'Vicious Mockery')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Bard'), (SELECT id FROM spells WHERE spell_name = 'Prestidigitation')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Bard'), (SELECT id FROM spells WHERE spell_name = 'Mage Hand')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Bard'), (SELECT id FROM spells WHERE spell_name = 'Healing Word')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Bard'), (SELECT id FROM spells WHERE spell_name = 'Dissonant Whispers')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Bard'), (SELECT id FROM spells WHERE spell_name = 'Detect Magic')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Bard'), (SELECT id FROM spells WHERE spell_name = 'Misty Step')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Bard'), (SELECT id FROM spells WHERE spell_name = 'Shatter')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Bard'), (SELECT id FROM spells WHERE spell_name = 'Hold Person')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Bard'), (SELECT id FROM spells WHERE spell_name = 'Hypnotic Pattern')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Bard'), (SELECT id FROM spells WHERE spell_name = 'Polymorph')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Bard'), (SELECT id FROM spells WHERE spell_name = 'Dominate Person')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Bard'), (SELECT id FROM spells WHERE spell_name = 'Otto''s Irresistible Dance')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Bard'), (SELECT id FROM spells WHERE spell_name = 'Etherealness')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Bard'), (SELECT id FROM spells WHERE spell_name = 'True Polymorph')) ON CONFLICT DO NOTHING;

-- Cleric
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Cleric'), (SELECT id FROM spells WHERE spell_name = 'Sacred Flame')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Cleric'), (SELECT id FROM spells WHERE spell_name = 'Guidance')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Cleric'), (SELECT id FROM spells WHERE spell_name = 'Toll the Dead')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Cleric'), (SELECT id FROM spells WHERE spell_name = 'Cure Wounds')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Cleric'), (SELECT id FROM spells WHERE spell_name = 'Bless')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Cleric'), (SELECT id FROM spells WHERE spell_name = 'Healing Word')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Cleric'), (SELECT id FROM spells WHERE spell_name = 'Detect Magic')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Cleric'), (SELECT id FROM spells WHERE spell_name = 'Hold Person')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Cleric'), (SELECT id FROM spells WHERE spell_name = 'Spiritual Weapon')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Cleric'), (SELECT id FROM spells WHERE spell_name = 'Aid')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Cleric'), (SELECT id FROM spells WHERE spell_name = 'Mass Healing Word')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Cleric'), (SELECT id FROM spells WHERE spell_name = 'Spirit Guardians')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Cleric'), (SELECT id FROM spells WHERE spell_name = 'Banishment')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Cleric'), (SELECT id FROM spells WHERE spell_name = 'Guardian of Faith')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Cleric'), (SELECT id FROM spells WHERE spell_name = 'Mass Cure Wounds')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Cleric'), (SELECT id FROM spells WHERE spell_name = 'Harm')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Cleric'), (SELECT id FROM spells WHERE spell_name = 'Resurrection')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Cleric'), (SELECT id FROM spells WHERE spell_name = 'Sunburst')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Cleric'), (SELECT id FROM spells WHERE spell_name = 'Holy Aura')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Cleric'), (SELECT id FROM spells WHERE spell_name = 'Mass Heal')) ON CONFLICT DO NOTHING;

-- Druid
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Druid'), (SELECT id FROM spells WHERE spell_name = 'Guidance')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Druid'), (SELECT id FROM spells WHERE spell_name = 'Shillelagh')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Druid'), (SELECT id FROM spells WHERE spell_name = 'Thunderclap')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Druid'), (SELECT id FROM spells WHERE spell_name = 'Cure Wounds')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Druid'), (SELECT id FROM spells WHERE spell_name = 'Detect Magic')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Druid'), (SELECT id FROM spells WHERE spell_name = 'Entangle')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Druid'), (SELECT id FROM spells WHERE spell_name = 'Moonbeam')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Druid'), (SELECT id FROM spells WHERE spell_name = 'Call Lightning')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Druid'), (SELECT id FROM spells WHERE spell_name = 'Conjure Animals')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Druid'), (SELECT id FROM spells WHERE spell_name = 'Polymorph')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Druid'), (SELECT id FROM spells WHERE spell_name = 'Dominate Beast')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Druid'), (SELECT id FROM spells WHERE spell_name = 'Wrath of Nature')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Druid'), (SELECT id FROM spells WHERE spell_name = 'Investiture of Flame')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Druid'), (SELECT id FROM spells WHERE spell_name = 'Earthquake')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Druid'), (SELECT id FROM spells WHERE spell_name = 'Foresight')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Druid'), (SELECT id FROM spells WHERE spell_name = 'Storm of Vengeance')) ON CONFLICT DO NOTHING;

-- Paladin
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Paladin'), (SELECT id FROM spells WHERE spell_name = 'Cure Wounds')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Paladin'), (SELECT id FROM spells WHERE spell_name = 'Bless')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Paladin'), (SELECT id FROM spells WHERE spell_name = 'Detect Magic')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Paladin'), (SELECT id FROM spells WHERE spell_name = 'Divine Smite')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Paladin'), (SELECT id FROM spells WHERE spell_name = 'Misty Step')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Paladin'), (SELECT id FROM spells WHERE spell_name = 'Hold Person')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Paladin'), (SELECT id FROM spells WHERE spell_name = 'Spiritual Weapon')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Paladin'), (SELECT id FROM spells WHERE spell_name = 'Aid')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Paladin'), (SELECT id FROM spells WHERE spell_name = 'Banishment')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Paladin'), (SELECT id FROM spells WHERE spell_name = 'Guardian of Faith')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Paladin'), (SELECT id FROM spells WHERE spell_name = 'Destructive Wave')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Paladin'), (SELECT id FROM spells WHERE spell_name = 'Holy Aura')) ON CONFLICT DO NOTHING;

-- Ranger
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Ranger'), (SELECT id FROM spells WHERE spell_name = 'Detect Magic')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Ranger'), (SELECT id FROM spells WHERE spell_name = 'Entangle')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Ranger'), (SELECT id FROM spells WHERE spell_name = 'Hunter''s Mark')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Ranger'), (SELECT id FROM spells WHERE spell_name = 'Misty Step')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Ranger'), (SELECT id FROM spells WHERE spell_name = 'Conjure Animals')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Ranger'), (SELECT id FROM spells WHERE spell_name = 'Polymorph')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Ranger'), (SELECT id FROM spells WHERE spell_name = 'Scrying')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Ranger'), (SELECT id FROM spells WHERE spell_name = 'Wrath of Nature')) ON CONFLICT DO NOTHING;

-- Sorcerer
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Sorcerer'), (SELECT id FROM spells WHERE spell_name = 'Fire Bolt')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Sorcerer'), (SELECT id FROM spells WHERE spell_name = 'Mage Hand')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Sorcerer'), (SELECT id FROM spells WHERE spell_name = 'Prestidigitation')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Sorcerer'), (SELECT id FROM spells WHERE spell_name = 'Thunderclap')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Sorcerer'), (SELECT id FROM spells WHERE spell_name = 'Magic Missile')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Sorcerer'), (SELECT id FROM spells WHERE spell_name = 'Shield')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Sorcerer'), (SELECT id FROM spells WHERE spell_name = 'Misty Step')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Sorcerer'), (SELECT id FROM spells WHERE spell_name = 'Scorching Ray')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Sorcerer'), (SELECT id FROM spells WHERE spell_name = 'Fireball')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Sorcerer'), (SELECT id FROM spells WHERE spell_name = 'Counterspell')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Sorcerer'), (SELECT id FROM spells WHERE spell_name = 'Polymorph')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Sorcerer'), (SELECT id FROM spells WHERE spell_name = 'Cone of Cold')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Sorcerer'), (SELECT id FROM spells WHERE spell_name = 'Dominate Person')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Sorcerer'), (SELECT id FROM spells WHERE spell_name = 'Chain Lightning')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Sorcerer'), (SELECT id FROM spells WHERE spell_name = 'Power Word Stun')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Sorcerer'), (SELECT id FROM spells WHERE spell_name = 'Wish')) ON CONFLICT DO NOTHING;

-- Warlock
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Warlock'), (SELECT id FROM spells WHERE spell_name = 'Eldritch Blast')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Warlock'), (SELECT id FROM spells WHERE spell_name = 'Prestidigitation')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Warlock'), (SELECT id FROM spells WHERE spell_name = 'Toll the Dead')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Warlock'), (SELECT id FROM spells WHERE spell_name = 'Hex')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Warlock'), (SELECT id FROM spells WHERE spell_name = 'Misty Step')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Warlock'), (SELECT id FROM spells WHERE spell_name = 'Hold Person')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Warlock'), (SELECT id FROM spells WHERE spell_name = 'Hunger of Hadar')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Warlock'), (SELECT id FROM spells WHERE spell_name = 'Banishment')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Warlock'), (SELECT id FROM spells WHERE spell_name = 'Blight')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Warlock'), (SELECT id FROM spells WHERE spell_name = 'Scrying')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Warlock'), (SELECT id FROM spells WHERE spell_name = 'Dominate Person')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Warlock'), (SELECT id FROM spells WHERE spell_name = 'Finger of Death')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Warlock'), (SELECT id FROM spells WHERE spell_name = 'Etherealness')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Warlock'), (SELECT id FROM spells WHERE spell_name = 'Power Word Stun')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Warlock'), (SELECT id FROM spells WHERE spell_name = 'True Polymorph')) ON CONFLICT DO NOTHING;

-- Wizard
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Wizard'), (SELECT id FROM spells WHERE spell_name = 'Fire Bolt')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Wizard'), (SELECT id FROM spells WHERE spell_name = 'Mage Hand')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Wizard'), (SELECT id FROM spells WHERE spell_name = 'Prestidigitation')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Wizard'), (SELECT id FROM spells WHERE spell_name = 'Magic Missile')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Wizard'), (SELECT id FROM spells WHERE spell_name = 'Shield')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Wizard'), (SELECT id FROM spells WHERE spell_name = 'Detect Magic')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Wizard'), (SELECT id FROM spells WHERE spell_name = 'Misty Step')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Wizard'), (SELECT id FROM spells WHERE spell_name = 'Hold Person')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Wizard'), (SELECT id FROM spells WHERE spell_name = 'Scorching Ray')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Wizard'), (SELECT id FROM spells WHERE spell_name = 'Fireball')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Wizard'), (SELECT id FROM spells WHERE spell_name = 'Counterspell')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Wizard'), (SELECT id FROM spells WHERE spell_name = 'Hypnotic Pattern')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Wizard'), (SELECT id FROM spells WHERE spell_name = 'Arcane Eye')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Wizard'), (SELECT id FROM spells WHERE spell_name = 'Polymorph')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Wizard'), (SELECT id FROM spells WHERE spell_name = 'Cone of Cold')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Wizard'), (SELECT id FROM spells WHERE spell_name = 'Scrying')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Wizard'), (SELECT id FROM spells WHERE spell_name = 'Chain Lightning')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Wizard'), (SELECT id FROM spells WHERE spell_name = 'Finger of Death')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Wizard'), (SELECT id FROM spells WHERE spell_name = 'Mordenkainen''s Sword')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Wizard'), (SELECT id FROM spells WHERE spell_name = 'Power Word Stun')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Wizard'), (SELECT id FROM spells WHERE spell_name = 'Wish')) ON CONFLICT DO NOTHING;
INSERT INTO class_spell VALUES ((SELECT id FROM classes WHERE class_name = 'Wizard'), (SELECT id FROM spells WHERE spell_name = 'True Polymorph')) ON CONFLICT DO NOTHING;